### ISSUE TITLE
Vậy giả sử hàm chưa được định nghĩa thì xử lý sao bạn ? 

### ISSUE THREAD

**Issue by m1nhn** [ngoc-nhu/baitap#3]
https://github.com/ngoc-nhu/baitap/blob/96069ec66a12c57e2ecf45629af0351443637f42/l%C3%BD%20thuy%E1%BA%BFt%20h%C3%A0m.txt#L25

**Comment by ngoc-nhu** [comment]
nếu như hàm chưa được định nghĩa thì khi gọi hàm sẽ bị lỗi
