### ISSUE TITLE
Vậy nếu giả sử mình cho a và b đều lớn thì bạn thử tính xem số phép tính mà máy tính cần phải thực hiện để tìm ra giá trị i của bạn ? Vậy nếu giả sử trường hợp a = b nữa thì bạn sẽ giải quyết vđ này như thế nào ? 

### ISSUE THREAD

**Issue by m1nhn** [ngoc-nhu/baitap#5]
https://github.com/ngoc-nhu/baitap/blob/427220d16865fed2a5fad3ae395fc5753c2bbefe/bai1.cpp#L5-L14

**Comment by ngoc-nhu** [comment]
thì trả về a

**Comment by ngoc-nhu** [comment]
thì trả về a

**Comment by ngoc-nhu** [comment]
return a

**Comment by m1nhn** [comment]
Trả về a. Vậy còn trường hợp a và b đều là những số lớn thì lúc này bạn sẽ giải quyết vấn đề này như thế nào ?

**Comment by ngoc-nhu** [comment]
nếu a và b đều là những số lớn thì code lại để giảm vòng lặp

**Comment by ngoc-nhu** [comment]
int UCLN(int a, int b) {
	if (a == b) {
		return a;
	}
	while (a != b) {
		if (a > b) {
			a = a - b;
		}
		else {
			b = b - a;
		}
	}
	return a;
}
