### ISSUE TITLE
Tuổi có quá được năm sinh với lại giả sử trường hợp tuổi < 0 thì sao nhỉ ? 

### ISSUE THREAD

**Issue by m1nhn** [ngoc-nhu/baitap#8]
https://github.com/ngoc-nhu/baitap/blob/427220d16865fed2a5fad3ae395fc5753c2bbefe/bai5.cpp#L9

**Comment by ngoc-nhu** [comment]
thì e bắt điều kiện
do {
		cout << " nhap tuoi ";
		cin >> n;
	} while (n < 0);
